import "./globals.css";
import Script from "next/script";
import React from "react";
import Footer from "@/Components/footer/Footer";
import Navbar from "@/Components/Navbar";

export const metadata = {
  title: "Farazaman | فرازمان",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Script
        src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"
        strategy="afterInteractive"
      />

      <html dir="rtl" lang="en">
        <body className="font-yakan bg-gray-50 drak: bg-transparent">
          <Navbar />
          <div className="mb-3">{children}</div>

          <Footer />
        </body>
      </html>
    </>
  );
}
